config/routes.rb
require 'resque-retry'
require 'resque-retry/server'

DocCenter::Application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'

  mount Resque::Server, :at => "/admin/resque", constraints: lambda {
   |request|
    request.env['warden'].authenticate!.has_role? :superadmin
  }

  ActiveAdmin.routes(self)

  resources :pages, :features
  resources :releases do
      get 'search', :on => :collection
  end

  match 'print/all/manuals'           => 'pages#print_all'
  match 'print/*path'                => 'pages#print'
  #match 'roadmap/*path'              => 'pages#show_roadmap',        :as => :roadmap

  root :to => "home#index"
  match 'search'                  => 'search#index',               :as => :search
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "dc_sessions" }, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  devise_scope :user do
    match '/login_proxy'            => 'dc_sessions#login_proxy', :as => :login_proxy
  end

  match 'sort_pages'                 => 'pages#sort',                :as => :sort_pages
  match 'sort_roadmaps'              => 'roadmaps#sort',             :as => :sort_roadmaps
  match 'redirect/login'             => 'redirect#login'


  namespace :api do
    namespace :v1 do
      match 'partners'               => 'partners#index'
      post  'partners/new'           => 'partners#new'
      put   'partners/update'        => 'partners#update'
      post  'partners/add_url'       => 'partners#add_to_existing'
      get   'search'                 => 'annotations#search', :defaults => { :format => :json }
      get   'annotations/resolve/:id'=> 'annotations#resolve', :defaults => { :format => :js }, :as => :annotation_resolve
      get   'annotations/user'       => 'annotations#user', :defaults => { :format => :json }
      resources :annotations, :defaults => { :format => :json }

    end
  end


  #TODO: figure out how to not declare these directly.
  post 'admin/pages/:id/rollback'    => 'admin/pages#rollback',      :as => :page_rollback
  post 'admin/releases/:id/rollback' => 'admin/releases#rollback',   :as => :release_rollback
  post 'admin/features/:id/rollback' => 'admin/features#rollback',   :as => :feature_rollback
  post 'admin/passages/:id/rollback' => 'admin/passages#rollback',   :as => :passage_rollback

  put 'autosave'                     => 'autosave#autosave',         :as => :autosave

  get 'updates'                      => 'updates#index'
  post '/dismiss_update_notice'      => 'updates#hide_update'


  post 'recent_changes'              => 'home#changes'
  post '/impersonate/:id'            => 'users/impersonation#impersonate'
  post '/unimpersonate'              => 'users/impersonation#unimpersonate'
  match '/users/iframesettings'            => 'users/settings#edit', :as => :user_iframesettings
  match 'users/settings'             => 'users/settings#settings', :as => :user_settings
  post '/users/update'               => 'users/settings#update', :as => :user_settings_update

  match 'users/test/:to'             => 'users/settings#test', :as => :test_email

  match '/magickly', :to => Magickly::App, :anchor => false
  match '/mark_as_read', :to => 'application#mark_as_read'
  get '/toggle_superadmin_only_mode', :to => 'application#toggle_superadmin_only_mode', constraints: lambda { |request|
    request.env['warden'].authenticate!.has_role? :superadmin
  }
  get '/admin/autocomplete_tags',
    to: 'admin/tags#autocomplete_tags',
    as: 'autocomplete_tags'

  match 'faqs'                       => 'faqs#index',                :as => :faqs
  match 'faqs/:tag'                  => 'faqs#show',                 :as => :faq_tag
  match 'faqs/show/:id'              => 'faqs#show_individual',      :as => :faq

  match 'fm/:fm_id'                  => 'public_pages#framemaker_redirect',  :as => :fm_redirect
  # don't put anything below these
  match '/roadmaps'       => 'roadmaps#index', :as => :roadmaps
  match '/roadmaps/*path' => 'roadmaps#show', :as => :roadmap

  #set up redirects for old /guides paths in case we have bookmarks
  match '/guides/*article'          => redirect('/manuals/%{article}')
  match '/guides/'                  => redirect('/manuals/')

  #set up redirects for marketplace/documentation/ articles
  match '/marketplace/documentation/invite-your-team' => redirect('/marketplace/getting-started/invite-your-team')
  match '/marketplace/documentation/invite-your-team/*path' => redirect('/marketplace/getting-started/invite-your-team/%{path}')
  match '/marketplace/documentation/configure-general-settings' => redirect('/marketplace/getting-started/configure-general-settings')
  match '/marketplace/documentation/configure-general-settings/*path' => redirect('/marketplace/getting-started/configure-general-settings/%{path}')
  match '/marketplace/documentation/configure-billing-settings' => redirect('/marketplace/getting-started/configure-billing-settings')
  match '/marketplace/documentation/configure-billing-settings/*path' => redirect('/marketplace/getting-started/configure-billing-settings/%{path}')
  match '/marketplace/documentation/configure-marketplace-functionality' => redirect('/marketplace/getting-started/configure-marketplace-functionality')
  match '/marketplace/documentation/configure-marketplace-functionality/*path' => redirect('/marketplace/getting-started/configure-marketplace-functionality/%{path}')
  match '/marketplace/documentation/customize-marketplace-ui' => redirect('/marketplace/getting-started/customize-marketplace-ui')
  match '/marketplace/documentation/customize-marketplace-ui/*path' => redirect('/marketplace/getting-started/customize-marketplace-ui/%{path}')
  match '/marketplace/documentation/merchandise-products' => redirect('/marketplace/getting-started/merchandise-products')
  match '/marketplace/documentation/merchandise-products/*path' => redirect('/marketplace/getting-started/merchandise-products/%{path}')
  match '/marketplace/documentation/sell-third-party-products' => redirect('/marketplace/getting-started/sell-third-party-products')
  match '/marketplace/documentation/sell-third-party-products/*path' => redirect('/marketplace/getting-started/sell-third-party-products/%{path}')
  match '/marketplace/documentation/sell-your-own-products' => redirect('/marketplace/getting-started/sell-your-own-products')
  match '/marketplace/documentation/sell-your-own-products/*path' => redirect('/marketplace/getting-started/sell-your-own-products/%{path}')
  match '/marketplace/documentation/manage-your-sales' => redirect('/marketplace/getting-started/manage-your-sales')
  match '/marketplace/documentation/manage-your-sales/*path' => redirect('/marketplace/getting-started/manage-your-sales/%{path}')
  match '/marketplace/documentation/additional-topics' => redirect('/marketplace/getting-started/additional-topics')
  match '/marketplace/documentation/additional-topics/*path' => redirect('/marketplace/getting-started/additional-topics/%{path}')
  
  match '/help-support/'          => 'supports#index', :as => "supports" # supports_path = /supports supports_url
  match '/help-support/*permalink' => "supports#show", :as => "support"

  match '/manuals'                 => 'pages#index', :as => :manuals
  match '/manuals/*path'           => 'pages#show', :as => :manual

  match '/isv-info'                => 'isv#index', :as => :isvinfos
  match '/isv-info/*path'          => 'isv#show', :as => :isvinfo
  #redirect for /billing to new /developer/billing
  match '/billing'                 => redirect('/developer/billing')
  match '/distribution'            => redirect('/developer/distribution')

  # ABSOLUTELY NOTHING BELOW THIS
  match '/help'                    => 'public_pages#index', :as => :help_center
  match '/*path'                   => 'public_pages#show', :as => :api

end

app/models/manual.rb
class Manual < Page
  # include Pdfable
  mapping = {
              manual: {
                dynamic_templates: [
                  { content: {
                      match: "*_content",
                      match_mapping_type: "string",
                      mapping: {
                        type: "string",
                        analyzer: "snowball",
                        index: "analyzed"
                      }
                  }}
                ],
                properties: {
                  title: { type: "string", analyzer: "snowball", index: "analyzed" },
                  permalink: { type: "string", analyzer: "keyword", index: "not_analyzed" },
                  public_content: { type: "string", analyzer: "snowball", index: "analyzed" },
                  date: { type: "date" }
                }
              }
            }

  searchkick merge_mappings: true, mappings: mapping, index_name: "manual_#{Rails.env}"
  def headline
    "Manuals"
  end

  def friendly_title
    title
  end

  def search_data
    generate_search_data_hash
  end

  def should_index?
    printable? #&& self.type != "Support" # only index published records
  end

  def generate_search_data_hash
    to_search = {}
    to_search["title"] = "#{title}"
    to_search["permalink"] = permalink
    to_search["public_content"] = format_field_for_search(self.body_contents)
    to_search["date"] = self.updated_at
    # ChannelPartner.all.each do |cp|
    #   to_search["#{cp.name.parameterize}_content"] = private_content(cp.id)
    # end
    return to_search
  end

  def private_content(id)
    channel_specific = channel_specific_contents.of(id).pluck(:content).join("") || ""
    return format_field_for_search(channel_specific)
  end

  def generate_permalink
    urls = self.ancestors.collect { |parent| parent.slug }
    urls.push self.slug
    # RAILS 4 TODO: If upgrading to Rails 4, change method to update_columns
    self.update_column(:permalink, "/manuals/#{urls.join('/')}")
  end
end

app/views/admin/manuals/_form.html.erb
<h2><%= @warn %></h2>
<%= semantic_form_for [:admin, @page], :html => { :data => { :class => "page", :id => @page.id } } do |f| %>  

    <%= f.inputs "Basic info" do %>
      <%= f.input :title %>
      <% pagez = Page.all.map { |c| ["-" * c.depth + c.title,c.id] }
      #Rails.logger.debug(pagez)
      if params[:parent_id]
        selected_index = params[:parent_id]
      elsif @page.parent_id != nil
        selected_index = @page.parent_id
      else
        selected_index = nil
      end

      status = @page.pub_status ||= "draft"
      %>
      <%= f.input :parent_id, :as => :select, :collection => options_for_select(pagez, selected_index) %>
      <%= f.input :pub_status, :as => :select, :collection => options_for_select([["Draft", "draft"], ["Published", "published"]], status), :include_blank => false %>
      <%= f.input :page_pub_date %>
      <%= f.input :file_upload, :as => :rich_picker, :config => { :style => 'width: 400px !important;' } %>
      <%= f.input :body, :as => :rich, :config => { :width => '76%', :height => '400px' } %>
      <% f.has_many :channel_specific do |cs| %>
        <%= cs.input :content %>
      <% end %>
    <% end %>
  <%= f.actions %>
<% end %>

app/views/admin/manuals/_index.html.erb
<ol class="pagelist sortable" data-sort-url="<%= sort_pages_path() %>">
  <% @manuals.each do |page| %>
    <% if page.parent_id == 0 || page.parent_id == nil %>
      <%= render "listitem", :page => page %>
    <% end %>
  <% end %>
</ol>

app/views/admin/manuals/_listitem.html.erb
<li id="list_<%= page.id %>" class="">
  <div class="for<%= page.id %> itemcontainer <%= 'no_children' if page.children.empty? %>">
    <span class="title"><%= link_to page.title, edit_admin_manual_path(:id => page.id) %><%= " (draft)" if page.pub_status == 'draft' %></span>
    <menu>
      <%= link_to("Create Child", new_admin_manual_path(:parent_id => page.id)) %>
      <%= link_to("Destroy", admin_manual_path(page), :method => :delete, :confirm => "Are you sure? This cannot be undone!") %>
    </menu>
    <%=raw "<span class='redirects'>redirects to first child &#x21b4;</span>" if page.redirect_to_first_child %>
    <span class="viewpage" id="view_for_<%= page.id %>"><%= link_to "View this page", page.permalink %></span>
  </div>
  <% if !page.children.empty? %>
    <ol>
      <% page.children.each do |child| %>
        <%= render "listitem", :page => child %>
      <% end %>
    </ol>
  <% end %>
</li>

app/views/admin/manuals/versions.html.erb
<% @page.versions.reverse_each do |v, i| %>
<div class="version">
  <%= render "admin/shared/vheading", :v => v %>
  <% if v.index + 1  == @page.versions.length %>
    <strong>Current Version</strong>
  <% else %>
    <%= link_to "Rollback to this version", page_rollback_path(:version => (v.id)), :method => :post %>
  <% end %>
  <%= render "admin/shared/diff", :v => v %>
</div>
<% end %>