config/routes.rb
require 'resque-retry'
require 'resque-retry/server'

DocCenter::Application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'

  mount Resque::Server, :at => "/admin/resque", constraints: lambda {
   |request|
    request.env['warden'].authenticate!.has_role? :superadmin
  }

  ActiveAdmin.routes(self)

  resources :pages, :features
  resources :releases do
      get 'search', :on => :collection
  end

  match 'print/all/manuals'           => 'pages#print_all'
  match 'print/*path'                => 'pages#print'
  #match 'roadmap/*path'              => 'pages#show_roadmap',        :as => :roadmap

  root :to => "home#index"
  match 'search'                  => 'search#index',               :as => :search
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "dc_sessions" }, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  devise_scope :user do
    match '/login_proxy'            => 'dc_sessions#login_proxy', :as => :login_proxy
  end

  match 'sort_pages'                 => 'pages#sort',                :as => :sort_pages
  match 'sort_roadmaps'              => 'roadmaps#sort',             :as => :sort_roadmaps
  match 'redirect/login'             => 'redirect#login'


  namespace :api do
    namespace :v1 do
      match 'partners'               => 'partners#index'
      post  'partners/new'           => 'partners#new'
      put   'partners/update'        => 'partners#update'
      post  'partners/add_url'       => 'partners#add_to_existing'
      get   'search'                 => 'annotations#search', :defaults => { :format => :json }
      get   'annotations/resolve/:id'=> 'annotations#resolve', :defaults => { :format => :js }, :as => :annotation_resolve
      get   'annotations/user'       => 'annotations#user', :defaults => { :format => :json }
      resources :annotations, :defaults => { :format => :json }

    end
  end


  #TODO: figure out how to not declare these directly.
  post 'admin/pages/:id/rollback'    => 'admin/pages#rollback',      :as => :page_rollback
  post 'admin/releases/:id/rollback' => 'admin/releases#rollback',   :as => :release_rollback
  post 'admin/features/:id/rollback' => 'admin/features#rollback',   :as => :feature_rollback
  post 'admin/passages/:id/rollback' => 'admin/passages#rollback',   :as => :passage_rollback

  put 'autosave'                     => 'autosave#autosave',         :as => :autosave

  get 'updates'                      => 'updates#index'
  post '/dismiss_update_notice'      => 'updates#hide_update'


  post 'recent_changes'              => 'home#changes'
  post '/impersonate/:id'            => 'users/impersonation#impersonate'
  post '/unimpersonate'              => 'users/impersonation#unimpersonate'
  match '/users/iframesettings'            => 'users/settings#edit', :as => :user_iframesettings
  match 'users/settings'             => 'users/settings#settings', :as => :user_settings
  post '/users/update'               => 'users/settings#update', :as => :user_settings_update

  match 'users/test/:to'             => 'users/settings#test', :as => :test_email

  match '/magickly', :to => Magickly::App, :anchor => false
  match '/mark_as_read', :to => 'application#mark_as_read'
  get '/toggle_superadmin_only_mode', :to => 'application#toggle_superadmin_only_mode', constraints: lambda { |request|
    request.env['warden'].authenticate!.has_role? :superadmin
  }
  get '/admin/autocomplete_tags',
    to: 'admin/tags#autocomplete_tags',
    as: 'autocomplete_tags'

  match 'faqs'                       => 'faqs#index',                :as => :faqs
  match 'faqs/:tag'                  => 'faqs#show',                 :as => :faq_tag
  match 'faqs/show/:id'              => 'faqs#show_individual',      :as => :faq

  match 'fm/:fm_id'                  => 'public_pages#framemaker_redirect',  :as => :fm_redirect
  # don't put anything below these
  match '/roadmaps'       => 'roadmaps#index', :as => :roadmaps
  match '/roadmaps/*path' => 'roadmaps#show', :as => :roadmap

  #set up redirects for old /guides paths in case we have bookmarks
  match '/guides/*article'          => redirect('/manuals/%{article}')
  match '/guides/'                  => redirect('/manuals/')

  #set up redirects for marketplace/documentation/ articles
  match '/marketplace/documentation/invite-your-team' => redirect('/marketplace/getting-started/invite-your-team')
  match '/marketplace/documentation/invite-your-team/*path' => redirect('/marketplace/getting-started/invite-your-team/%{path}')
  match '/marketplace/documentation/configure-general-settings' => redirect('/marketplace/getting-started/configure-general-settings')
  match '/marketplace/documentation/configure-general-settings/*path' => redirect('/marketplace/getting-started/configure-general-settings/%{path}')
  match '/marketplace/documentation/configure-billing-settings' => redirect('/marketplace/getting-started/configure-billing-settings')
  match '/marketplace/documentation/configure-billing-settings/*path' => redirect('/marketplace/getting-started/configure-billing-settings/%{path}')
  match '/marketplace/documentation/configure-marketplace-functionality' => redirect('/marketplace/getting-started/configure-marketplace-functionality')
  match '/marketplace/documentation/configure-marketplace-functionality/*path' => redirect('/marketplace/getting-started/configure-marketplace-functionality/%{path}')
  match '/marketplace/documentation/customize-marketplace-ui' => redirect('/marketplace/getting-started/customize-marketplace-ui')
  match '/marketplace/documentation/customize-marketplace-ui/*path' => redirect('/marketplace/getting-started/customize-marketplace-ui/%{path}')
  match '/marketplace/documentation/merchandise-products' => redirect('/marketplace/getting-started/merchandise-products')
  match '/marketplace/documentation/merchandise-products/*path' => redirect('/marketplace/getting-started/merchandise-products/%{path}')
  match '/marketplace/documentation/sell-third-party-products' => redirect('/marketplace/getting-started/sell-third-party-products')
  match '/marketplace/documentation/sell-third-party-products/*path' => redirect('/marketplace/getting-started/sell-third-party-products/%{path}')
  match '/marketplace/documentation/sell-your-own-products' => redirect('/marketplace/getting-started/sell-your-own-products')
  match '/marketplace/documentation/sell-your-own-products/*path' => redirect('/marketplace/getting-started/sell-your-own-products/%{path}')
  match '/marketplace/documentation/manage-your-sales' => redirect('/marketplace/getting-started/manage-your-sales')
  match '/marketplace/documentation/manage-your-sales/*path' => redirect('/marketplace/getting-started/manage-your-sales/%{path}')
  match '/marketplace/documentation/additional-topics' => redirect('/marketplace/getting-started/additional-topics')
  match '/marketplace/documentation/additional-topics/*path' => redirect('/marketplace/getting-started/additional-topics/%{path}')
  
  match '/help-support/'          => 'supports#index', :as => "supports" # supports_path = /supports supports_url
  match '/help-support/*permalink' => "supports#show", :as => "support"

  match '/manuals'                 => 'pages#index', :as => :manuals
  match '/manuals/*path'           => 'pages#show', :as => :manual

  match '/isv-info'                => 'isv#index', :as => :isvinfos
  match '/isv-info/*path'          => 'isv#show', :as => :isvinfo
  #redirect for /billing to new /developer/billing
  match '/billing'                 => redirect('/developer/billing')
  match '/distribution'            => redirect('/developer/distribution')

  # ABSOLUTELY NOTHING BELOW THIS
  match '/help'                    => 'public_pages#index', :as => :help_center
  match '/*path'                   => 'public_pages#show', :as => :api

end

app/models/faq.rb
class Faq < ActiveRecord::Base
  resourcify #Used by rolify
  acts_as_taggable
  include Searchable
  extend FriendlyId
  friendly_id :question, use: [:slugged]

  attr_accessible :question,
                  :answer,
                  :pub_status,
                  :tag_list,
                  :slug

  validates_presence_of :question, :answer

  searchkick merge_mappings: true, mappings: {
              faq: {
                dynamic_templates: [
                  { content: {
                      match: "*_content",
                      match_mapping_type: "string",
                      mapping: {
                        type: "string",
                        analyzer: "snowball",
                        index: "analyzed"
                      }
                  }}
                ],
                properties: {
                  title: { type: "string", analyzer: "snowball", index: "analyzed" },
                  public_content: { type: "string", analyzer: "snowball", index: "analyzed" },
                  date: { type: "date" }
                }
              }
            }

  def search_data
    generate_search_data_hash
  end

  def generate_search_data_hash
    to_search = {}
    to_search["title"] = "#{question}"
    to_search["public_content"] = format_field_for_search(self.answer)
    to_search["date"] = self.updated_at
    # ChannelPartner.all.each do |cp|
    #   to_search["#{cp.name.parameterize}_content"] = ""
    # end
    return to_search
  end

  def friendly_title
    question
  end

  def title
    question
  end

  def headline
    "FAQs"
  end
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  include RestrictedPartners
  layout 'pages'
  before_filter :tag_nav

  def index
    @faqs = Faq.all
  end

  def show
    tag_filter = params[:tag].titleize
    @faqs = Faq.tagged_with(tag_filter)
  end

  def show_individual
    @faq = Faq.find(params[:id])
  end

  def tag_nav
    @faq_nav = Faq.tag_counts_on(:tags) #this returns an array of tag objects that we can pull the name out of for the nav
  end
  # def tag_count
  #   @tags = FAQ.tag_counts
  # end
end

app/views/faqs/_leftnav.html.haml
%nav.left-col.side
  %ul.faq_nav
    %li
      %h2.h6.all-caps
        Categories
      %ul.side-nav
        - @faq_nav.each do |tag|
          %li{ :class => "#{selected_if_path_includes(tag.name.parameterize)} channel_color_border simple-navigation-active-leaf" }
            %a{ :href => "/faqs/#{tag.name.parameterize}", :class => "#{selected_if_path_includes(tag.name.parameterize)} channel_color_border" }= tag.name.titleize

app/views/faqs/_search_header.html.haml
= form_tag search_path, method: :get, class: 'search_form' do
  = text_field_tag :q, params[:q], :placeholder => 'Search FAQs', :class => 'icons-magnifying_glass'
  = hidden_field_tag :index, "Faq"
  = submit_tag "GO", name: nil

app/views/faqs/index.html.haml
%section.container.three-nine-three
  %header
    %h1.h2= t :headline, :scope => :faqs
    = render 'search_header'
  = render 'leftnav'
  %article.middle-col.channel_color_headlines
    - @faq_nav.each do |cat|
      %h3.channel_color
        %a{ :href => "/faqs/#{cat.name.parameterize}" }
          = cat.name
      - if cat.description.present?
        %p= cat.description.description

    -# %ul.list-reset.item_list
    -#   - @faqs.each do |faq|
    -#     %li.spy_this{:id => faq.question.parameterize}
    -#       %h3.channel_color= faq.question
    -#       .answer
    -#         = raw faq.answer
  %aside.right-col
    -# .fix_wrap
    -#   %h2.h6.all-caps Contents
    -#   %nav#jumpnav
    -#     %ul.side-nav.jumpnav.nav.right
    -#       - @faqs.each do |faq|
    -#         %li
    -#           %a.channel_color_border{:href => "##{faq.question.parameterize}"}= faq.question

app/views/faqs/show.html.haml
%section.container.three-nine-three
  %header
    %h1.h2= t :headline, :scope => :faqs
    = render 'search_header'
  = render 'leftnav'
  %article.middle-col.channel_color_headlines
    %ul.list-reset.item_list
      - if @faqs.empty?
        %p Sorry, no FAQs exist in that category.
      - else
        - @faqs.each do |faq|
          %li.spy_this{:id => faq.question.parameterize}
            %h3.channel_color= faq.question
            .answer
              = raw faq.answer
  %aside.right-col
    .fix_wrap
      %h2.h6.all-caps Contents
      %nav#jumpnav
        %ul.side-nav.jumpnav.nav.right
          - @faqs.each do |faq|
            %li
              %a.channel_color_border{:href => "##{faq.question.parameterize}"}= faq.question

app/views/faqs/show_individual.html.haml
%section.container.three-nine-three
  %header
    %h1.h2= t :headline, :scope => :faqs
    = render 'search_header'
  = render 'leftnav'
  %article.middle-col.channel_color_headlines
    %ul.list-reset.item_list
      %li.spy_this{:id => @faq.question.parameterize}
        %h3.channel_color= @faq.question
        .answer
          = raw @faq.answer
  %aside.right-col