config/routes.rb
require 'resque-retry'
require 'resque-retry/server'

DocCenter::Application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'

  mount Resque::Server, :at => "/admin/resque", constraints: lambda {
   |request|
    request.env['warden'].authenticate!.has_role? :superadmin
  }

  ActiveAdmin.routes(self)

  resources :pages, :features
  resources :releases do
      get 'search', :on => :collection
  end

  match 'print/all/manuals'           => 'pages#print_all'
  match 'print/*path'                => 'pages#print'
  #match 'roadmap/*path'              => 'pages#show_roadmap',        :as => :roadmap

  root :to => "home#index"
  match 'search'                  => 'search#index',               :as => :search
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "dc_sessions" }, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  devise_scope :user do
    match '/login_proxy'            => 'dc_sessions#login_proxy', :as => :login_proxy
  end

  match 'sort_pages'                 => 'pages#sort',                :as => :sort_pages
  match 'sort_roadmaps'              => 'roadmaps#sort',             :as => :sort_roadmaps
  match 'redirect/login'             => 'redirect#login'


  namespace :api do
    namespace :v1 do
      match 'partners'               => 'partners#index'
      post  'partners/new'           => 'partners#new'
      put   'partners/update'        => 'partners#update'
      post  'partners/add_url'       => 'partners#add_to_existing'
      get   'search'                 => 'annotations#search', :defaults => { :format => :json }
      get   'annotations/resolve/:id'=> 'annotations#resolve', :defaults => { :format => :js }, :as => :annotation_resolve
      get   'annotations/user'       => 'annotations#user', :defaults => { :format => :json }
      resources :annotations, :defaults => { :format => :json }

    end
  end


  #TODO: figure out how to not declare these directly.
  post 'admin/pages/:id/rollback'    => 'admin/pages#rollback',      :as => :page_rollback
  post 'admin/releases/:id/rollback' => 'admin/releases#rollback',   :as => :release_rollback
  post 'admin/features/:id/rollback' => 'admin/features#rollback',   :as => :feature_rollback
  post 'admin/passages/:id/rollback' => 'admin/passages#rollback',   :as => :passage_rollback

  put 'autosave'                     => 'autosave#autosave',         :as => :autosave

  get 'updates'                      => 'updates#index'
  post '/dismiss_update_notice'      => 'updates#hide_update'


  post 'recent_changes'              => 'home#changes'
  post '/impersonate/:id'            => 'users/impersonation#impersonate'
  post '/unimpersonate'              => 'users/impersonation#unimpersonate'
  match '/users/iframesettings'            => 'users/settings#edit', :as => :user_iframesettings
  match 'users/settings'             => 'users/settings#settings', :as => :user_settings
  post '/users/update'               => 'users/settings#update', :as => :user_settings_update

  match 'users/test/:to'             => 'users/settings#test', :as => :test_email

  match '/magickly', :to => Magickly::App, :anchor => false
  match '/mark_as_read', :to => 'application#mark_as_read'
  get '/toggle_superadmin_only_mode', :to => 'application#toggle_superadmin_only_mode', constraints: lambda { |request|
    request.env['warden'].authenticate!.has_role? :superadmin
  }
  get '/admin/autocomplete_tags',
    to: 'admin/tags#autocomplete_tags',
    as: 'autocomplete_tags'

  match 'faqs'                       => 'faqs#index',                :as => :faqs
  match 'faqs/:tag'                  => 'faqs#show',                 :as => :faq_tag
  match 'faqs/show/:id'              => 'faqs#show_individual',      :as => :faq

  match 'fm/:fm_id'                  => 'public_pages#framemaker_redirect',  :as => :fm_redirect
  # don't put anything below these
  match '/roadmaps'       => 'roadmaps#index', :as => :roadmaps
  match '/roadmaps/*path' => 'roadmaps#show', :as => :roadmap

  #set up redirects for old /guides paths in case we have bookmarks
  match '/guides/*article'          => redirect('/manuals/%{article}')
  match '/guides/'                  => redirect('/manuals/')

  #set up redirects for marketplace/documentation/ articles
  match '/marketplace/documentation/invite-your-team' => redirect('/marketplace/getting-started/invite-your-team')
  match '/marketplace/documentation/invite-your-team/*path' => redirect('/marketplace/getting-started/invite-your-team/%{path}')
  match '/marketplace/documentation/configure-general-settings' => redirect('/marketplace/getting-started/configure-general-settings')
  match '/marketplace/documentation/configure-general-settings/*path' => redirect('/marketplace/getting-started/configure-general-settings/%{path}')
  match '/marketplace/documentation/configure-billing-settings' => redirect('/marketplace/getting-started/configure-billing-settings')
  match '/marketplace/documentation/configure-billing-settings/*path' => redirect('/marketplace/getting-started/configure-billing-settings/%{path}')
  match '/marketplace/documentation/configure-marketplace-functionality' => redirect('/marketplace/getting-started/configure-marketplace-functionality')
  match '/marketplace/documentation/configure-marketplace-functionality/*path' => redirect('/marketplace/getting-started/configure-marketplace-functionality/%{path}')
  match '/marketplace/documentation/customize-marketplace-ui' => redirect('/marketplace/getting-started/customize-marketplace-ui')
  match '/marketplace/documentation/customize-marketplace-ui/*path' => redirect('/marketplace/getting-started/customize-marketplace-ui/%{path}')
  match '/marketplace/documentation/merchandise-products' => redirect('/marketplace/getting-started/merchandise-products')
  match '/marketplace/documentation/merchandise-products/*path' => redirect('/marketplace/getting-started/merchandise-products/%{path}')
  match '/marketplace/documentation/sell-third-party-products' => redirect('/marketplace/getting-started/sell-third-party-products')
  match '/marketplace/documentation/sell-third-party-products/*path' => redirect('/marketplace/getting-started/sell-third-party-products/%{path}')
  match '/marketplace/documentation/sell-your-own-products' => redirect('/marketplace/getting-started/sell-your-own-products')
  match '/marketplace/documentation/sell-your-own-products/*path' => redirect('/marketplace/getting-started/sell-your-own-products/%{path}')
  match '/marketplace/documentation/manage-your-sales' => redirect('/marketplace/getting-started/manage-your-sales')
  match '/marketplace/documentation/manage-your-sales/*path' => redirect('/marketplace/getting-started/manage-your-sales/%{path}')
  match '/marketplace/documentation/additional-topics' => redirect('/marketplace/getting-started/additional-topics')
  match '/marketplace/documentation/additional-topics/*path' => redirect('/marketplace/getting-started/additional-topics/%{path}')
  
  match '/help-support/'          => 'supports#index', :as => "supports" # supports_path = /supports supports_url
  match '/help-support/*permalink' => "supports#show", :as => "support"

  match '/manuals'                 => 'pages#index', :as => :manuals
  match '/manuals/*path'           => 'pages#show', :as => :manual

  match '/isv-info'                => 'isv#index', :as => :isvinfos
  match '/isv-info/*path'          => 'isv#show', :as => :isvinfo
  #redirect for /billing to new /developer/billing
  match '/billing'                 => redirect('/developer/billing')
  match '/distribution'            => redirect('/developer/distribution')

  # ABSOLUTELY NOTHING BELOW THIS
  match '/help'                    => 'public_pages#index', :as => :help_center
  match '/*path'                   => 'public_pages#show', :as => :api

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper
  def index
    if current_user
      # stuff for authenticated users.
      @current_release = Release.current_release
      @cr_has_content ||= @current_release.any_content_for?(current_user) if @current_release
      # @welcome = current_user.quickstart
      if current_user.channel_partner
        @support_links = get_links.find_all { |l| l.link_type == "support" }
        @general_links = get_links.find_all { |l| l.link_type == "links" }
      end
      @welcome = current_user.quickstart
    else
      redirect_to "/help"
      #redirect_to "/developer"
    end
  end

  def changes
    date = params[:date]
    @updates = organize_response(get_recent_changes(date))
    respond_to do |format|
      format.json { render :json => @updates }
    end
  end

  private

  def organize_response(updates)
    ofthejedi = []
    updates.each do |update|
      next if update.class.to_s == "Release" && !update.any_content_for?(current_user)
      ud = {
        :title => update.friendly_title,
        :section => update.headline,
        :klass => sort_pages(update),
        :section_link => generate_section_link(update),
        :last_update => update.updated_at.strftime("%B %d, %Y"),
        :published_on => update.created_at.strftime("%B %d, %Y"),
        :action => format_update_item(update),
        :id => update.id,
        :status => update.unread?(current_user) ? "Unread" : "Read",
        :link => generate_link(update),
        :merged => check_feature(update),
        :read_on => read_date(update)
      }

      ofthejedi << ud
    end
    return ofthejedi
  end

  def read_date(update)
    if update.read_marks.empty?
      return ""
    else
      update.read_marks.first.timestamp.strftime("%B %d, %Y")
    end
  end

  def check_feature(update)
    return false unless update.class.to_s == "Feature"
    if update.release != nil
      return "Merged into #{update.release.title}"
    else
      false
    end
  end

  def generate_section_link(update)

    if update.class.to_s == "Roadmap"
      return "/roadmaps"
    elsif update.class.to_s == "Manual"
      return "/manuals"
    elsif update.class.to_s == "Api"
      return update.root.permalink
    else
      return view_context.url_for(update.class)
    end
  end

  def generate_link(update)
    update.respond_to?('permalink') ?
      update.permalink :
      view_context.url_for(update)
  end

  def sort_pages(update)
    s = update.class.to_s
    return s unless s == "Page"
    if update.is_guide?
      return "Guide"
    else
      return "Page"
    end
  end

  def get_links
    @links ||= current_user.channel_partner.custom_links
  end

  def get_recent_changes(time)
    time = time || current_user.last_sign_in_at
    (  release_changes(time) +
       guide_changes(time) +
       roadmap_changes(time)

      #Feature.created_or_updated_since(time, current_user)
    ).sort { |a,b| a.updated_at <=> b.updated_at }
  end

  def guide_changes(time)
    if current_user.channel_partner.able_to_see_user_guides?
      Manual.created_or_updated_since(time, current_user)
    else
      []
    end
  end

  def roadmap_changes(time)
    if current_user.channel_partner.able_to_see_roadmaps?
      # skip the root nodes since the years don't have any actual content
      Roadmap.from_depth(1).created_or_updated_since(time, current_user)
    else
      []
    end
  end

  def release_changes(time)
    if current_user.channel_partner.able_to_see_releases?
      Release.created_or_updated_since(time, current_user)
    else
      []
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
  def format_update_item update
    # determine type of update
    if update.class.to_s == "Feature" && !update.merge_date.blank?
      "Merged"
    elsif update.class.to_s == "Release" && !update.hotfixes_for(current_user).blank? && update.hotfixes_for(current_user).last.updated_at > update.updated_at
      "Hotfix #{update.hotfixes_for(current_user).last.number}"
    elsif update.updated_at > update.created_at
      "Updated"
    else
      "Published"
    end
    # output different strings based on Class and action
    # case update.class.to_s 
    # when "Page"
    #   if action == "create"
    #     return "Added #{update.title}"
    #   else
    #     return "Updated #{update.title}"
    #   end
    # when "Release"
    #   if action == "create"
    #     return "Release #{update.title} Has Been Posted"
    #   else
    #     return "Release #{update.title} Has Been Updated"
    #   end
    # when "Feature"
    #   if action == "create"
    #     return "Upcoming Feature: #{update.title}"
    #   else
    #     return "Feature #{update.title} Has Been Updated"
    #   end
    # end
  end
end

app/views/home/_updates_table.html.haml
.updates_table{"data-seven" => 7.days.ago.to_date, "data-thirty" => 30.days.ago.to_date}
  %header
    %menu.main_tabs
      %ul.nav-tabs
        %li.active
          %a{"data-toggle" => "tab", :href => "#recently_published"}
            Recently Published
            %span#rp_count.count 0
        %li
          %a{"data-toggle" => "tab", :href => "#changes"} Changes
  .tab-content
    #recently_published.tab-pane.active
      %header
        %menu.time_select
          %a#rp_time_unread{"data-range" => "unread", "data-scope" => "unread", :href => "#"} Unread Only
          %a#rp_time_30days{"data-range" => "30_days", "data-scope" => 30.days.ago.to_date, :href => "#"} Last 30 Days
      %table
        %thead
          %tr
            %th.title Title
            %th.section Section
            %th.date Date Posted
        %tbody#rp_tbody
    #changes.tab-pane
      %header
        %menu.time_select
          %a#c_time_7days.c_first.active{"data-range" => "7_days", "data-scope" => 7.days.ago.to_date, :href => "#"} Last Week
          %a#c_time_30days{"data-range" => "30_days", "data-scope" => 30.days.ago.to_date, :href => "#"} Last 30 Days
      %table
        %thead
          %tr
            %th.c_title Title
            %th.c_section Section
            %th.c_action Action
            %th.c_date Date Posted
        %tbody#changes_tbody


%script{ :type => "text/html", :id => "recently_published_template" }
  %tr{:class => "{{ status.toLowerCase() }}"}
    %td.title.linkable
      %a{:href => "{{ link }}"} {{ title }}
      %div{:class => "indicator channel_color_background_hover {{ status.toLowerCase() }}", "data-read-on" => "{{ read_on }}", "data-resource-id" => "{{ klass }}-{{ id }}"}
        .prefix
          %ul
            %li.check
            %li.spinner-small
            %li.un UN
        READ
    %td.linkable
      %a.icon{:class => "icons-{{ klass.toLowerCase() }}", :href => "{{  section_link }}"} {{ section }}
    %td {{ date }}

%script{ :type => "text/html", :id => "changes_template" }
  %tr
    %td.title.linkable
      %a{:href => "{{ link }}"} {{ title }}
    %td.linkable
      %a.icon{:class => "icons-{{ klass.toLowerCase() }}", :href => "{{ section_link }}"} {{ section }}
    %td
      %div{:class => "indicator {{ action.toLowerCase() }}"}
        {{ action_message() }}
    %td {{ date }}

app/views/home/anon_home.html.haml
.container
  %h1 Hello Anonymous...

app/views/home/index.html.haml
.container
  %header
    - unless current_user.channel_partner.logo.blank?
      = image_tag magick(current_user.channel_partner.logo, resize: 230), class: "partner_logo" , alt: "#{current_user.channel_partner.name} Logo"
    %h1.h2 Documentation Center
= render 'welcome'
.container.home
  .twelve-three
    %section.left-col= render 'updates_table'
    %aside.right-col
      - if @current_release && current_user.channel_partner.able_to_see_releases?
        %div{class: "current_container widget #{'empty_release' unless @cr_has_content}"}
          %h2.h6= t :current, :scope => :home
          %h1{title: "release number", class: "number_box small channel_color_background headline_reset current_release"}
            = link_to_if @cr_has_content, "#{@current_release.title}", release_path(@current_release)
          %ul.release_footer_links
            - if @cr_has_content
              - release_notes_count = @current_release.count_notes_for(current_user) ? @current_release.count_notes_for(current_user) : 0
              - if release_notes_count > 0
                %li= link_to t(:channel_specific_headline, :scope => :releases), release_path(@current_release, :anchor => "channel_specific"), :class => "channel_color"
              %li= link_to t('short_pdf', scope: :releases), release_path(@current_release, format: :pdf), :class => "channel_color"
            - else
              %li= t(:no_content, :scope => :releases)
      - unless current_user.channel_partner.account_reps.blank?
        .widget
          %h2.h6= t :account_rep, :scope => :home
          - current_user.channel_partner.account_reps.each do |account_rep|
            = render 'rep_card', :account_rep => account_rep
      - unless @support_links.blank?
        .widget
          %h2.h6= t :support, :scope => :home
          %ul.support_links
            - @support_links.each do |link|
              %li
                %a{href: link.url, target: "_blank"}= link.label
        - #since the marketplace url is used here, this section will never be blank?
        .widget
          %h2.h6= t :links, :scope => :home
          %ul.custom_links
            %li= link_to "Your Marketplace", marketplace_url
            - @general_links.each do |link|
              %li
                %a{href: link.url, target: "_blank"}= link.label
- if false
  .middle-col
    .updated_content
      %h2.h6= @updates[:title]
      %ul
        - @updates[:data].reverse.each do |update|
          - link = update.class.to_s.downcase == "page" ? update.permalink : update
          %li
            = link_to truncate_html(format_update_item(update), :length => 75, :omission => '...'), link, {:class => "icons-#{update.class.to_s.downcase}"}
            = raw datetime_to_date update.updated_at, true